### ISSUE TITLE
Mage registry key "_singleton/fpc/observer_save" already exists

### ISSUE THREAD

**Issue by seansan** [mage-eag/mage-enhanced-admin-grids#158]
Hi, we saw this error this morning. And cannot access the order anymore (clicking the orde rgives this error). Can this be grid related? (seeing it just before)

Mage registry key "_singleton/fpc/observer_save" already exists

Trace:
#0 /app/Mage.php(243): Mage::throwException('Mage registry k...')
#1 /app/Mage.php(498): Mage::register('_singleton/fpc/...', false)
#2 /app/code/core/Mage/Core/Model/App.php(1316): Mage::getSingleton('fpc/observer_sa...')
#3 /app/Mage.php(468): Mage_Core_Model_App->dispatchEvent('model_save_afte...', Array)
#4 /app/code/core/Mage/Core/Model/Abstract.php(465): Mage::dispatchEvent('model_save_afte...', Array)
#5 /app/code/community/BL/CustomGrid/Model/Grid.php(252): Mage_Core_Model_Abstract->_afterSave()
#6 /app/code/core/Mage/Core/Model/Abstract.php(319): BL_CustomGrid_Model_Grid->_afterSave()
#7 /app/code/community/BL/CustomGrid/Model/Grid.php(1278): Mage_Core_Model_Abstract->save()
#8 /app/code/community/BL/CustomGrid/Model/Observer.php(554): BL_CustomGrid_Model_Grid->checkColumnsAgainstGridBlock(Object(BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Sales_Order_View_Tab_Creditmemos))
#9 /app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(93): BL_CustomGrid_Model_Observer->afterGridPrepareCollection(Object(BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Sales_Order_View_Tab_Creditmemos))
#10 /app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Sales_Order_View_Tab_Creditmemos->_prepareCollection()
#11 /app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#12 /app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#13 /app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(303): Mage_Core_Block_Abstract->toHtml()
#14 /app/design/adminhtml/default/default/template/widget/tabs.phtml(38): Mage_Adminhtml_Block_Widget_Tabs->getTabContent(Object(BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Sales_Order_View_Tab_Creditmemos))
#15 /app/code/core/Mage/Core/Block/Template.php(246): include('/home/shirts350...')
#16 /app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#17 /app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#18 /app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#19 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#20 /app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#21 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#22 /app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#23 /app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#24 /app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#25 /app/code/core/Mage/Core/Block/Template.php(246): include('/home/shirts350...')
#26 /app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#27 /app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#28 /app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#29 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#30 /app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#31 /app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#32 /app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(128): Mage_Core_Controller_Varien_Action->renderLayout()
#33 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->viewAction()
#34 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#35 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#36 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#37 /app/Mage.php(705): Mage_Core_Model_App->run(Array)
#38 /index.php(89): Mage::run('default', 'store')
#39 {main}

**Comment by seansan** [comment]
Fixed, sorry
