### ISSUE TITLE
Extension appears to be causing duplicate customers

### ISSUE THREAD

**Issue by Wingo64** [mage-eag/mage-enhanced-admin-grids#201]
<b>Version 0.8.9 beta</b>

When I try to access the "Manage Customer" function on magento. I get the error “<b>Item (Mage_Customer_Model_Customer) with the same id “xxx” already exist</b>”). I usually clear this by manually deleting duplicate records from magento table customer_entity_int.

I get the same error when I try to edit a customer in magento admin. But in this case, no matter how many times I delete the duplicate records from customer_entity_int, as soon as I try to edit a customer from Magento admin, I get the error and four additional records in customer_entity_int.

I posted on the forums and received the feedback that the stack trace (see below) suggests that your enhanced grids extension might be to causing this issue. 

I would be very grateful if you could look into this problem and advise me on how to fix it. Ideally I would like to stop the duplicate records being created in the first place.

Many Thanks

Trace:
#0 /---/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(265): Varien_Data_Collection->addItem(Object(Mage_Customer_Model_Customer))
#1 /---/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1057): Mage_Eav_Model_Entity_Collection_Abstract->addItem(Object(Mage_Customer_Model_Customer))
#2 /---/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#3 /---/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Mage_Eav_Model_Entity_Collection_Abstract->load()
#4 /---/app/code/core/Mage/Adminhtml/Block/Customer/Grid.php(61): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#5 /---/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(96): Mage_Adminhtml_Block_Customer_Grid->_prepareCollection()
#6 /---/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(382): BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Customer_Grid->_prepareCollection()
#7 /---/app/code/community/BL/CustomGrid/Model/Observer.php(562): BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Customer_Grid->blcg_finishPrepareCollection()
#8 /---/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(93): BL_CustomGrid_Model_Observer->afterGridPrepareCollection(Object(BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Customer_Grid))
#9 /---/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Customer_Grid->_prepareCollection()
#10 /---/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#11 /---/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#12 /---/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#13 /---/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#14 /---/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#15 /---/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#16 /---/app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/ma...')
#17 /---/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#18 /---/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#19 /---/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#20 /---/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#21 /---/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#22 /---/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#23 /---/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#24 /---/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#25 /---/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#26 /---/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#27 /---/app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/ma...')
#28 /---/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#29 /---/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#30 /---/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#31 /---/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#32 /---/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#33 /---/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#34 /---/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(83): Mage_Core_Controller_Varien_Action->renderLayout()
#35 /---/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CustomerController->indexAction()
#36 /---/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#37 /---/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#38 /---/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#39 /---/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#40 /---/index.php(88): Mage::run('', 'store')
#41 {main}

**Comment by Wingo64** [comment]
I have since uninstalled the extension and still get the same problem ultimate exception - although the trace output is different. So I guess you can close this as a non-issue although I would be very grateful if anybody can offer any advice on how to fix this issue or get closer to the root cause,
Thanks

**Comment by Wingo64** [comment]
Closing as a non-issue. 
If anyone knows how to prevent duplicate records being created in magento's customer_entity_int table, then I would be grateful for details
