### ISSUE TITLE
There has been an error processing your request

### ISSUE THREAD

**Issue by santosjoni** [mage-eag/mage-enhanced-admin-grids#221]
Just after install I'm getting this error when I try to  go to catalog product. Any idea?

error report: 
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'infotati_magento.customgrid_role_profile' doesn't exist, query was: SELECT DISTINCT `cgg`.`grid_id`, `ar`.`role_id`, `cggr`.`permissions`, `cggr`.`default_profile_id`, `cgrp`.`profile_id` FROM `customgrid_grid` AS `cgg`
 INNER JOIN `admin_role` AS `ar`
 LEFT JOIN `customgrid_grid_role` AS `cggr` ON (cggr.role_id = ar.role_id) AND (cggr.grid_id = cgg.grid_id)
 LEFT JOIN `customgrid_grid_profile` AS `cggp` ON cggp.grid_id = cgg.grid_id
 LEFT JOIN `customgrid_role_profile` AS `cgrp` ON (cgrp.role_id = ar.role_id) AND (cgrp.profile_id = cggp.profile_id) WHERE (ar.role_type = 'G') AND (cgg.grid_id IN ('1', '6', '7', '8', '9', '10', '11'))

Trace:
#0 /home/infotati/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/infotati/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/infotati/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/infotati/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT DISTINCT...', Array)
#4 /home/infotati/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SELECT DISTINCT...', Array)
#5 /home/infotati/public_html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /home/infotati/public_html/app/code/community/BL/CustomGrid/Model/Mysql4/Grid.php(396): Zend_Db_Adapter_Abstract->fetchAll(Object(Varien_Db_Select))
#7 /home/infotati/public_html/app/code/community/BL/CustomGrid/Model/Mysql4/Grid/Collection.php(76): BL_CustomGrid_Model_Mysql4_Grid->getGridRoles(Array)
#8 /home/infotati/public_html/app/code/community/BL/CustomGrid/Model/Mysql4/Grid/Collection.php(26): BL_CustomGrid_Model_Mysql4_Grid_Collection->addRolesConfigToResult()
#9 /home/infotati/public_html/lib/Varien/Data/Collection/Db.php(581): BL_CustomGrid_Model_Mysql4_Grid_Collection->_afterLoad()
#10 /home/infotati/public_html/app/code/community/BL/CustomGrid/Model/Observer.php(133): Varien_Data_Collection_Db->load()
#11 /home/infotati/public_html/app/code/community/BL/CustomGrid/Model/Observer.php(394): BL_CustomGrid_Model_Observer->getGridModelsCollection()
#12 /home/infotati/public_html/app/code/core/Mage/Core/Model/App.php(1338): BL_CustomGrid_Model_Observer->onControllerActionPreDispatch(Object(Varien_Event_Observer))
#13 /home/infotati/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(BL_CustomGrid_Model_Observer), 'onControllerAct...', Object(Varien_Event_Observer))
#14 /home/infotati/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#15 /home/infotati/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#16 /home/infotati/public_html/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#17 /home/infotati/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#18 /home/infotati/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#19 /home/infotati/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#20 /home/infotati/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#21 /home/infotati/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#22 /home/infotati/public_html/index.php(97): Mage::run('', 'store')
#23 {main}`

**Comment by mage-eag** [comment]
Seems like the setup has not been fully completed, can you try to trigger it again ? (delete the `customgrid_setup` row in the `core_resource` table when your website is under maintenance, and refresh the cache if necessary)

**Comment by santosjoni** [comment]
Thanks for your response!!
I'm having a different error now:

Error in file: "/home/infotati/public_html/beta/app/code/community/BL/CustomGrid/sql/customgrid_setup/mysql4-install-1.0.0.1.php" - SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'base_profile_id' doesn't exist in table

Trace:
#0 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '1.0.0.1')
#2 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('1.0.0.1')
#3 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /home/infotati/public_html/beta/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /home/infotati/public_html/beta/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/infotati/public_html/beta/index.php(87): Mage::run('', 'store')
#8 {main}

**Comment by mage-eag** [comment]
Was it actually a version upgrade rather than a first-time install ?
Because in the upgrade case, the solution is different from re-triggering an install : update the `customgrid_setup` row from the `core_resource` table by setting both version fields at `0.8.9` (then in your case, you may have to re-create the row if this hasn't been automatically done when re-installing).

In any case, this still seems to be an unfinished setup bug, but you may also have to adapt the upgrade script a little bit, depending on which steps have been successfully applied before the setup ended. This is due to the fact that some steps can't be applied twice, and is the reason why installs or upgrades should always be done under maintenance - race conditions can easily happen, and require quite some clean-up before the setup can be launched again.

**Comment by Forestsoft-de** [comment]
Same here fresh install of Extension:

Base table or view not found: 1146 Table 'ilpshop.customgrid_grid' doesn't exist

The problem is that the setup script isnt executed but the observer already try to get the data from table.


here is an stack trace:

```
#0 /var/www/shop/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/shop/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /var/www/shop/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /var/www/shop/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /var/www/shop/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/shop/lib/Zend/Db/Adapter/Abstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /var/www/shop/lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /var/www/shop/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /var/www/shop/lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /var/www/shop/app/code/community/BL/CustomGrid/Model/Observer.php(133): Varien_Data_Collection_Db->load()
#10 /var/www/shop/app/code/community/BL/CustomGrid/Model/Observer.php(394): BL_CustomGrid_Model_Observer->getGridModelsCollection()
#11 /var/www/shop/app/code/core/Mage/Core/Model/App.php(1338): BL_CustomGrid_Model_Observer->onControllerActionPreDispatch(Object(Varien_Event_Observer))
#12 /var/www/shop/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(BL_CustomGrid_Model_Observer), 'onControllerAct...', Object(Varien_Event_Observer))
#13 /var/www/shop/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#14 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(528): Mage::dispatchEvent('controller_acti...', Array)
#15 /var/www/shop/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#16 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(408): Mage_Adminhtml_Controller_Action->preDispatch()
#17 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#18 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /var/www/shop/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#20 /var/www/shop/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#21 /var/www/shop/index.php(86): Mage::run('', 'store')
#22 {main}

**Comment by saranara** [comment]
I have same problem after i upgrade 1.9.2.2 from 1.9.2.1 please advice me about re installation 1.9.2.2

**Comment by seansan** [comment]
same error here

reset core resource not solution

**Comment by seansan** [comment]
@Forestsoft-de Did you solve the upgrade? (not triggering the observer first)

**Comment by Forestsoft-de** [comment]
@seansan no i have had implement on my own because we needed only 2 columns :)
