### ISSUE TITLE
Column not found: 1054 Unknown column 'blcg_custom_field_1' in 'where clause'

### ISSUE THREAD

**Issue by seansan** [mage-eag/mage-enhanced-admin-grids#250]
We see this error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blcg_custom_field_1' in 'where clause'

We changed store name colum to only inlclude the storename (1 row). 
Now when we filter on a certain store the error occurs

See image

![image](https://cloud.githubusercontent.com/assets/652395/11686574/d194ca86-9e81-11e5-9ba8-3533b4f56609.png)

with reference to https://github.com/mage-eag/mage-enhanced-admin-grids/issues/65

**Comment by seansan** [comment]
Ps. most urgent now is that it crashed the complete grid and we cannot access it anymore (workaround is to clear session/cookies and to not filter again)

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blcg_custom_field_1' in 'where clause'

Trace:
#0 /home/user/domains/store.com/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/user/domains/store.com/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/user/domains/store.com/public_html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/user/domains/store.com/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT DISTINCT...', Array)
#4 /home/user/domains/store.com/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT DISTINCT...', Array)
#5 /home/user/domains/store.com/public_html/lib/Zend/Db/Adapter/Abstract.php(828): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /home/user/domains/store.com/public_html/lib/Varien/Data/Collection/Db.php(225): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/code/community/BL/CustomGrid/Model/Grid/Rewriter/Eval.php(32) : eval()'d code(353): Varien_Data_Collection_Db->getSize()
#8 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/code/community/BL/CustomGrid/Block/Widget/Grid/Columns/Config/Additional.php(108): BL_CustomGrid_Block_Rewrite_Mage_Adminhtml_Block_Sales_Order_Grid->blcg_getCollectionSize()
#9 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/columns/config/additional.phtml(240): BL_CustomGrid_Block_Widget_Grid_Columns_Config_Additional->getGridSize()
#10 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(247): include('/home/user...')
#11 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#12 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#13 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#14 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/code/community/BL/CustomGrid/Block/Widget/Grid/Columns/Config/Abstract.php(31): Mage_Adminhtml_Block_Template->_toHtml()
#15 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): BL_CustomGrid_Block_Widget_Grid_Columns_Config_Abstract->_toHtml()
#16 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/code/community/BL/CustomGrid/Block/Widget/Grid/Columns/Config.php(185): Mage_Core_Block_Abstract->toHtml()
#17 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/columns/config.phtml(82): BL_CustomGrid_Block_Widget_Grid_Columns_Config->getAdditionalHtml()
#18 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(247): include('/home/user...')
#19 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#20 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#21 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#22 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/code/community/BL/CustomGrid/Block/Widget/Grid/Columns/Config.php(245): Mage_Adminhtml_Block_Template->_toHtml()
#23 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): BL_CustomGrid_Block_Widget_Grid_Columns_Config->_toHtml()
#24 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#25 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('bl_custom_grid_...', true)
#26 /home/user/domains/store.com/public_html/.modman/mage-enhanced-admin-grids/app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/16.phtml(68): Mage_Core_Block_Abstract->getChildHtml('bl_custom_grid_...')
#27 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(247): include('/home/user...')
#28 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#29 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#30 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#31 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#32 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#33 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#34 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#35 /home/user/domains/store.com/public_html/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#36 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(247): include('/home/user...')
#37 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#38 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#39 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#40 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#41 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#42 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#43 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#44 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#45 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#46 /home/user/domains/store.com/public_html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#47 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(247): include('/home/user...')
#48 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(278): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#49 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Template.php(292): Mage_Core_Block_Template->renderView()
#50 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#51 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#52 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#53 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#54 /home/user/domains/store.com/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(95): Mage_Core_Controller_Varien_Action->renderLayout()
#55 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->indexAction()
#56 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#57 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#58 /home/user/domains/store.com/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#59 /home/user/domains/store.com/public_html/app/Mage.php(705): Mage_Core_Model_App->run(Array)
#60 /home/user/domains/store.com/public_html/index.php(105): Mage::run('soh_nl', 'store')
#61 {main}

Error log record number: 424752250813

```

**Comment by seansan** [comment]
this is happening rather often ... and it is always blcg_custom_field_1 of blcg_custom_field_2 or blcg_custom_field_6 or blcg_custom_field_7 .... 

is this something we can help debug? or a known issue?

many thanks, Sean
