### ISSUE TITLE
Mage registry key "_singleton/customgrid/observer" already exists

### ISSUE THREAD

**Issue by deckside** [mage-eag/mage-enhanced-admin-grids#299]
Hi 
After installing it worked for a few hours and now I cannot get into the admin screen unless I uninstall.

This is the full error message

Thank you in advance

Mage registry key "_singleton/customgrid/observer" already exists

Trace:
#0 /opt/bitnami/apps/magento/htdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /opt/bitnami/apps/magento/htdocs/app/Mage.php(477): Mage::register('_singleton/cust...', false)
#2 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(22147): Mage::getSingleton('customgrid/obse...')
#3 /opt/bitnami/apps/magento/htdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(14381): Mage::dispatchEvent('controller_acti...', Array)
#5 /opt/bitnami/apps/magento/htdocs/includes/src/Mage_Adminhtml_Controller_Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#6 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(14261): Mage_Adminhtml_Controller_Action->preDispatch()
#7 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(18750): Mage_Core_Controller_Varien_Action->dispatch('login')
#8 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(18280): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /opt/bitnami/apps/magento/htdocs/includes/src/__default.php(21176): Mage_Core_Controller_Varien_Front->dispatch()
#10 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /opt/bitnami/apps/magento/htdocs/index.php(83): Mage::run('', 'store')
#12 {main}

**Comment by deckside** [comment]
I found the problem.

I forgot to "Run Compilation Process" after installing.

OOPs
