### ISSUE TITLE
Fatal error: Class 'BL_CustomGrid_Helper_Data' 

### ISSUE THREAD

**Issue by newyorkwebdesign** [mage-eag/mage-enhanced-admin-grids#349]
Just manually uploaded to Magento test server. Logged out of admin and recieved: "Fatal error: Class 'BL_CustomGrid_Helper_Data' not found in /home/shop_production/htdocs/app/Mage.php on line 547" error. Please advise. Thanks!

**Comment by newyorkwebdesign** [comment]
Here is some other errors:

`Mage registry key "_singleton/customgrid/observer" already exists

Trace:
#0 /home/shop_production/htdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home/shop_production/htdocs/app/Mage.php(477): Mage::register('_singleton/cust...', false)
#2 /home/shop_production/htdocs/includes/src/__default.php(22262): Mage::getSingleton('customgrid/obse...')
#3 /home/shop_production/htdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /home/shop_production/htdocs/includes/src/__default.php(14442): Mage::dispatchEvent('controller_acti...', Array)
#5 /home/shop_production/htdocs/includes/src/Mage_Adminhtml_Controller_Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#6 /home/shop_production/htdocs/includes/src/__default.php(14322): Mage_Adminhtml_Controller_Action->preDispatch()
#7 /home/shop_production/htdocs/includes/src/__default.php(18825): Mage_Core_Controller_Varien_Action->dispatch('login')
#8 /home/shop_production/htdocs/includes/src/__default.php(18355): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/shop_production/htdocs/includes/src/__default.php(21291): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/shop_production/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/shop_production/htdocs/index.php(83): Mage::run('', 'store')
#12 {main}`

**Comment by newyorkwebdesign** [comment]
Manually turned off compilation and I'm back in business: https://github.com/mage-eag/mage-enhanced-admin-grids/issues/41
