### ISSUE TITLE
EAG - Errors

### ISSUE THREAD

**Issue by nohart** [mage-eag/mage-enhanced-admin-grids#87]
This is a great extension and I have have just updated to v0.8.9 on Magento v1.7.0.2 but I occasionally get EAG - Errors. How do I remove them?

Here is one I have now -

An error occured while rewriting "M2ePro/adminhtml_ebay_order_view_log" : "The original class "Ess_M2ePro_Block_Adminhtml_Ebay_Order_View_Log" does not exist" (rewriter: "eval")

Should I just look this up under - System -> Custom Grids -> List -> Manage Custom Grids - 

M2ePro/adminhtml_ebay_order_view_log

and "Delete" it?

This is what I did for a previous error and now I don't get that error anymore, but I want to make sure I am not breaking the extension because I am not sure if deleting it is the right thing to do. Thanks again for the great extension!

**Comment by elvarcro** [comment]
Hi,

I have same issue with AW_AdvancedNewsletter Subcriber list.

If I delete the custom grid It works once but then it generates automatically again and again I have the same error.

You cannot define a correlation name 'store' more than once

Trace:
#0 /lib/Varien/Db/Select.php(281): Zend_Db_Select->_join('inner join', Array, 'store.store_id ...', Array, NULL)
#1 /lib/Zend/Db/Select.php(336): Varien_Db_Select->_join('inner join', Array, 'store.store_id ...', Array, NULL)
